export const data = {
  questions: [
    {
      category: "science",
      id: "622a1c377cc59eab6f950476",
      correctAnswer:
        "wounds and injuries caused by accidents or assaults and their surgical treatment and repair",
      incorrectAnswers: [
        "karyotypes",
        "alternative method of massage, manipulative therapy|therapy or pressure on certain points of the sole of the feet as a means of relieving nervous tension",
        "plants; botany",
      ],
      question: {
        text: "What is Traumatology the study of?",
      },
      tags: ["science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "6242cb19d543524f1b19c90c",
      correctAnswer: "A school",
      incorrectAnswers: ["A parliament", "A clowder", "A stud"],
      question: {
        text: "What is the word for a group of dolphins?",
      },
      tags: ["science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "645cb0ee602ff42ca52fb41b",
      correctAnswer: "Sedimentary",
      incorrectAnswers: ["Metamorphic", "Igneous", "Volcanic"],
      question: {
        text: "What is the name of the one of the three main types of rocks that gets its name from the Latin word meaning 'to settle'?",
      },
      tags: ["geology", "science", "latin", "words"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "648889175dba6c873ef650e2",
      correctAnswer: "The suspension system",
      incorrectAnswers: [
        "The transmission system",
        "The steering system",
        "The braking system",
      ],
      question: {
        text: "What is the term for the system in your car that includes the springs, dampers and other parts responsible for shock absorption?",
      },
      tags: ["cars", "engineering", "technology", "motoring", "science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "622a1c377cc59eab6f9504a3",
      correctAnswer: "mental processes in living creatures",
      incorrectAnswers: [
        "the study and psychology of organisms with regard to their functions and structures",
        "Semitic cultures",
        "the characteristics of the skull",
      ],
      question: {
        text: "What is Psychology the study of?",
      },
      tags: ["science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "622a1c377cc59eab6f950531",
      correctAnswer:
        "relationships within families particularly with a view to constructing family trees",
      incorrectAnswers: ["the age of the Earth", "plankton", "primates"],
      question: {
        text: "What is Genealogy the study of?",
      },
      tags: ["science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "645b9ebcf09106226db23570",
      correctAnswer: "Centigrade",
      incorrectAnswers: ["Fahrenheit", "Kelvin", "Rankine"],
      question: {
        text: 'What is the other name for the Celsius temperature scale, meaning "divided into one hundred parts"?',
      },
      tags: ["chemistry", "physics", "measurements", "science", "words"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "622a1c377cc59eab6f9504af",
      correctAnswer: "rays, usually ionising radiation",
      incorrectAnswers: [
        "the specialty in medicine that deals with diseases of the lungs and the respiratory tract",
        "the same as otolaryngology",
        "the moon",
      ],
      question: {
        text: "What is Radiology the study of?",
      },
      tags: ["words", "science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "6243345ccfaae40c1296143b",
      correctAnswer: "A Piglet",
      incorrectAnswers: ["A Leveret", "A Tadpole", "A Bunny"],
      question: {
        text: "What is the word for a young hedgehog?",
      },
      tags: ["science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
    {
      category: "science",
      id: "622a1c3a7cc59eab6f95107f",
      correctAnswer: "Rubber",
      incorrectAnswers: ["Plastic", "Iron", "Wood"],
      question: {
        text: "To What Is The Process Of Vulcanisation Applied?",
      },
      tags: ["science"],
      type: "text_choice",
      difficulty: "medium",
      regions: [],
      isNiche: false,
    },
  ],
};
